version: "3.8"
services:
  frontend:
    image: nginx:alpine
    depends_on:
      - backend
    environment:
      - API_BASE_URL=http://backend:8080

  backend:
    image: FULLWORDGAME_ACR_LOGIN_SERVER/backend:APP_TAG
    environment:
      - ASPNETCORE_URLS=http://+:8080
