version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wordgame-backend
    ports:
      - "5000:8080"

  frontend:
    build:
      context: ./wordgame-frontend
    container_name: wordgame-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
